---
collections:
  - name: ansible.posix
    version: "2.1.0"
  - name: community.vmware
    version: "6.2.0"
  - name: community.crypto
    version: "3.1.1"
  - name: community.hashi_vault
    version: "7.1.0"
  - name: fedora.linux_system_roles
    version: "1.120.5"
  - name: lit.supplementary
    version: "1.16.12"
  - name: lit.foundational
    version: "1.16.0"
  - name: lit.rhel
    version: "1.9.7"
