---
ansible-navigator:
  ansible-runner:
    artifact-dir: /runner/project/.ansible-runner
    rotate-artifacts-count: 10
  execution-environment:
    enabled: true
    container-engine: podman
    # Default image (public profile). Override at runtime with:
    # ANSIBLE_TOOLBOX_NAV_EE_IMAGE=<image:tag>
    image: quay.io/l-it/ee-wunder-ansible-ubi9:v1.10.0
    pull:
      policy: missing
    container-options:
      - "--network=slirp4netns"
    environment-variables:
      pass:
        - ANSIBLE_VAULT_PASSWORD_FILE
        - VAULT_TOKEN
      set:
        ANSIBLE_CONFIG: /runner/project/ansible.cfg
        ANSIBLE_LOCAL_TEMP: /tmp
        ANSIBLE_REMOTE_TEMP: /tmp
        ANSIBLE_COLLECTIONS_PATH: "/opt/modulix/ansible/collections-dev:/opt/modulix/ansible/collections:/runner/project/collections-dev:/runner/project/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections:/runner/collections"
  mode: stdout
  playbook-artifact:
    enable: false
